ALTER TABLE cobrade ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE cobrade ALTER COLUMN description TYPE VARCHAR(1000);
ALTER TABLE cobrade ALTER COLUMN subgroup TYPE VARCHAR(250);
ALTER TABLE cobrade ALTER COLUMN type TYPE VARCHAR(500);
ALTER TABLE cobrade ALTER COLUMN subtype TYPE VARCHAR(500);
ALTER TABLE cobrade ADD COLUMN origin VARCHAR(20);

INSERT INTO cobrade (origin, group_name, code, subgroup, type, subtype, description) VALUES
-- DESASTRES NATURAIS 
-- 1. GEOLÓGICO
('Naturais','Geológico','1.1.1.1.0', 'Terremoto', 'Tremor de terra', NULL, 'Vibrações do terreno que provocam oscilações verticais e horizontais na superfície da Terra (ondas sísmicas). Pode ser natural (tectônica) ou induzido (explosões, injeção profunda de líquidos e gás, extração de fluidos, alívio de carga de minas, enchimento de lagos artificiais).'),
('Naturais','Geológico','1.1.1.2.0', 'Terremoto', 'Tsunami', NULL, 'Série de ondas geradas por deslocamento de um grande volume de água causado geralmente por terremotos, erupções vulcânicas ou movimentos de massa.'),
('Naturais','Geológico','1.1.2.0.0', 'Emanação vulcânica', NULL, NULL, 'Produtos/materiais vulcânicos lançados na atmosfera a partir de erupções vulcânicas.'),
('Naturais','Geológico','1.1.3.1.1', 'Movimento de massa', 'Quedas, tombamentos e rolamentos', 'Blocos', 'As quedas de blocos são movimentos rápidos e acontecem quando materiais rochosos diversos e de volumes variáveis se destacam de encostas muito íngremes, num movimento tipo queda livre. Os tombamentos de blocos são movimentos de massa em que ocorre rotação de um bloco de solo ou rocha em torno de um ponto ou abaixo do centro de gravidade da massa desprendida. Rolamentos de blocos são movimentos de blocos rochosos ao longo de encostas, que ocorrem geralmente pela perda de apoio (descalçamento).'),
('Naturais','Geológico','1.1.3.1.2', 'Movimento de massa', 'Quedas, tombamentos e rolamentos', 'Lascas', 'As quedas de lascas são movimentos rápidos e acontecem quando fatias delgadas formadas pelos fragmentos de rochas se destacam de encostas muito íngremes, num movimento tipo queda livre.'),
('Naturais','Geológico','1.1.3.1.3', 'Movimento de massa', 'Quedas, tombamentos e rolamentos', 'Matacões', 'Os rolamentos de matacões são caracterizados por movimentos rápidos e acontecem quando materiais rochosos diversos e de volumes variáveis se destacam de encostas e movimentam-se num plano inclinado.'),
('Naturais','Geológico','1.1.3.1.4', 'Movimento de massa', 'Quedas, tombamentos e rolamentos', 'Lajes', 'As quedas de lajes são movimentos rápidos e acontecem quando fragmentos de rochas extensas de superfície mais ou menos plana e de pouca espessura se destacam de encostas muito íngremes, num movimento tipo queda livre.'),
('Naturais','Geológico','1.1.3.2.1', 'Movimento de massa', 'Deslizamentos', 'Deslizamentos de solo e/ou rocha', 'São movimentos rápidos de solo ou rocha, apresentando superfície de ruptura bem definida, de duração relativamente curta, de massas de terreno geralmente bem definidas quanto ao seu volume, cujo centro de gravidade se desloca para baixo e para fora do talude. Frequentemente, os primeiros sinais desses movimentos são a presença de fissuras.'),
('Naturais','Geológico','1.1.3.3.1', 'Movimento de massa', 'Corridas de massa', 'Solo/Lama', 'Ocorrem quando, por índices pluviométricos excepcionais, o solo/lama, misturado com a água, tem comportamento de líquido viscoso, de extenso raio de ação e alto poder destrutivo.'),
('Naturais','Geológico','1.1.3.3.2', 'Movimento de massa', 'Corridas de massa', 'Rocha/Detrito', 'Ocorrem quando, por índices pluviométricos excepcionais, rocha/detrito, misturado com a água, tem comportamento de líquido viscoso, de extenso raio de ação e alto poder destrutivo.'),
('Naturais','Geológico','1.1.3.4.0', 'Movimento de massa', 'Subsidências e colapsos', NULL, 'Afundamento rápido ou gradual do terreno devido ao colapso de cavidades, redução da porosidade do solo ou deformação de material argiloso.'),
('Naturais','Geológico','1.1.4.1.0', 'Erosão', 'Erosão costeira/Marinha', NULL, 'Processo de desgaste (mecânico ou químico) que ocorre ao longo da linha da costa (rochosa ou praia) e se deve à ação das ondas, correntes marinhas e marés.'),
('Naturais','Geológico','1.1.4.2.0', 'Erosão', 'Erosão de margem fluvial', NULL, 'Desgaste das encostas dos rios que provoca desmoronamento de barrancos.'),
('Naturais','Geológico','1.1.4.3.1', 'Erosão', 'Erosão continental', 'Laminar', 'Remoção de uma camada delgada e uniforme do solo superficial provocada por fluxo hídrico não concentrado.'),
('Naturais','Geológico','1.1.4.3.2', 'Erosão', 'Erosão continental', 'Ravinas', 'Evolução, em tamanho e profundidade, da desagregação e remoção das partículas do solo de sulcos provocada por escoamento hídrico superficial concentrado.'),
('Naturais','Geológico','1.1.4.3.3', 'Erosão', 'Erosão continental', 'Boçorocas', 'Evolução do processo de ravinamento, em tamanho e profundidade, em que a desagregação e remoção das partículas do solo são provocadas por escoamento hídrico superficial e subsuperficial (escoamento freático) concentrado.'),
-- 2. HIDROLÓGICO
('Naturais','Hidrológico','1.2.1.0.0', 'Inundações', NULL, NULL, 'Submersão de áreas fora dos limites normais de um curso de água em zonas que normalmente não se encontram submersas. O transbordamento ocorre de modo gradual, geralmente ocasionado por chuvas prolongadas em áreas de planície.'),
('Naturais','Hidrológico','1.2.2.0.0', 'Enxurradas', NULL, NULL, 'Escoamento superficial de alta velocidade e energia, provocado por chuvas intensas e concentradas, normalmente em pequenas bacias de relevo acidentado. Caracterizada pela elevação súbita das vazões de determinada drenagem e transbordamento brusco da calha fluvial. Apresenta grande poder destrutivo.'),
('Naturais','Hidrológico','1.2.3.0.0', 'Alagamentos', NULL, NULL, 'Extrapolação da capacidade de escoamento de sistemas de drenagem urbana e consequente acúmulo de água em ruas, calçadas ou outras infraestruturas urbanas, em decorrência de precipitações intensas.'),
-- 3. METEOROLÓGICO
('Naturais','Meteorológico','1.3.1.1.1', 'Sistemas de grande escala/Escala regional', 'Ciclones', 'Ventos costeiros (mobilidade de dunas)', 'Intensificação dos ventos nas regiões litorâneas, movimentando dunas de areia sobre construções na orla.'),
('Naturais','Meteorológico','1.3.1.1.2', 'Sistemas de grande escala/Escala regional', 'Ciclones', 'Marés de tempestade (ressaca)', 'São ondas violentas que geram uma maior agitação do mar próximo à praia. Ocorrem quando rajadas fortes de vento fazem subir o nível do oceano em mar aberto e essa intensificação das correntes marítimas carrega uma enorme quantidade de água em direção ao litoral. Em consequência, as praias inundam, as ondas se tornam maiores e a orla pode ser devastada alagando ruas e destruindo edificações.'),
('Naturais','Meteorológico','1.3.1.2.0', 'Sistemas de grande escala/Escala regional', 'Frentes frias/Zonas de convergência', NULL, 'Frente fria é uma massa de ar frio que avança sobre uma região, provocando queda brusca da temperatura local, com período de duração inferior à friagem. Zona de convergência é uma região que está ligada à tempestade causada por uma zona de baixa pressão atmosférica, provocando forte deslocamento de massas de ar, vendavais, chuvas intensas e até queda de granizo.'),
('Naturais','Meteorológico','1.3.2.1.1', 'Tempestades', 'Tempestade local/Convectiva', 'Tornados', 'Coluna de ar que gira de forma violenta e muito perigosa, estando em contato com a terra e a base de uma nuvem de grande desenvolvimento vertical. Essa coluna de ar pode percorrer vários quilômetros e deixa um rastro de destruição pelo caminho percorrido.'),
('Naturais','Meteorológico','1.3.2.1.2', 'Tempestades', 'Tempestade local/Convectiva', 'Tempestade de raios', 'Tempestade com intensa atividade elétrica no interior das nuvens, com grande desenvolvimento vertical.'),
('Naturais','Meteorológico','1.3.2.1.3', 'Tempestades', 'Tempestade local/Convectiva', 'Granizo', 'Precipitação de pedaços irregulares de gelo.'),
('Naturais','Meteorológico','1.3.2.1.4', 'Tempestades', 'Tempestade local/Convectiva', 'Chuvas intensas', 'São chuvas que ocorrem com acumulados significativos, causando múltiplos desastres (ex.: inundações, movimentos de massa, enxurradas, etc.).'),
('Naturais','Meteorológico','1.3.2.1.5', 'Tempestades', 'Tempestade local/Convectiva', 'Vendaval', 'Forte deslocamento de uma massa de ar em uma região.'),
('Naturais','Meteorológico','1.3.3.1.0', 'Temperaturas extremas', 'Onda de calor', NULL, 'É um período prolongado de tempo excessivamente quente e desconfortável, onde as temperaturas ficam acima de um valor normal esperado para aquela região em determinado período do ano. Geralmente adotado um período mínimo de três dias com temperaturas $5^{\circ}C$ acima dos valores máximos médios.'),
('Naturais','Meteorológico','1.3.3.2.1', 'Temperaturas extremas', 'Onda de frio', 'Friagem', 'Período de tempo que dura, no mínimo, de três a quatro dias, e os valores de temperatura mínima do ar ficam abaixo dos valores esperados para determinada região em um período do ano.'),
('Naturais','Meteorológico','1.3.3.2.2', 'Temperaturas extremas', 'Onda de frio', 'Geadas', 'Formação de uma camada de cristais de gelo na superfície ou na folhagem exposta.'),
-- 4. CLIMATOLÓGICO
('Naturais','Climatológico','1.4.1.1.0', 'Seca', 'Estiagem', NULL, 'Período prolongado de baixa ou nenhuma pluviosidade, em que a perda de umidade do solo é superior à sua reposição.'),
('Naturais','Climatológico','1.4.1.2.0', 'Seca', 'Seca', NULL, 'A seca é uma estiagem prolongada, durante o período de tempo suficiente para que a falta de precipitação provoque grave desequilíbrio hidrológico.'),
('Naturais','Climatológico','1.4.1.3.1', 'Incêndio florestal', 'Incêndios em parques, áreas de proteção ambiental e áreas de preservação permanente nacionais, estaduais ou municipais', NULL, 'Propagação de fogo sem controle, em qualquer tipo de vegetação situada em áreas legalmente protegidas.'),
('Naturais','Climatológico','1.4.1.3.2', 'Incêndio florestal', 'Incêndios em áreas não protegidas, com reflexos na qualidade do ar', NULL, 'Propagação de fogo sem controle, em qualquer tipo de vegetação que não se encontre em áreas sob proteção legal, acarretando queda da qualidade do ar.'),
('Naturais','Climatológico','1.4.1.4.0', 'Climatológico', 'Baixa umidade do ar', NULL, 'Queda da taxa de vapor de água suspensa na atmosfera para níveis abaixo de 20%.'),
-- 5. BIOLÓGICO
('Naturais','Biológico','1.5.1.1.0', 'Epidemias', 'Doenças infecciosas virais', NULL, 'Aumento brusco, significativo e transitório da ocorrência de doenças infecciosas geradas por vírus.'),
('Naturais','Biológico','1.5.1.2.0', 'Epidemias', 'Doenças infecciosas bacterianas', NULL, 'Aumento brusco, significativo e transitório da ocorrência de doenças infecciosas geradas por bactérias.'),
('Naturais','Biológico','1.5.1.3.0', 'Epidemias', 'Doenças infecciosas parasiticas', NULL, 'Aumento brusco, significativo e transitório da ocorrência de doenças infecciosas geradas por parasitas.'),
('Naturais','Biológico','1.5.1.4.0', 'Epidemias', 'Doenças infecciosas fúngicas', NULL, 'Aumento brusco, significativo e transitório da ocorrência de doenças infecciosas geradas por fungos.'),
('Naturais','Biológico','1.5.2.1.0', 'Infestações/Pragas', 'Infestações de animais', NULL, 'Infestações por animais que alterem o equilíbrio ecológico de uma região, bacia hidrográfica ou bioma afetado por suas ações predatórias.'),
('Naturais','Biológico','1.5.2.2.1', 'Infestações/Pragas', 'Infestações de algas', 'Marés vermelhas', 'Aglomeração de microalgas em água doce ou em água salgada suficiente para causar alterações físicas, químicas ou biológicas em sua composição, caracterizada por uma mudança de cor, tornando-se amarela, laranja, vermelha ou marrom.'),
('Naturais','Biológico','1.5.2.2.2', 'Infestações/Pragas', 'Infestações de algas', 'Cianobactérias em reservatórios', 'Aglomeração de cianobactérias em reservatórios receptores de descargas de dejetos domésticos, industriais e/ou agrícolas, provocando alterações das propriedades físicas, químicas ou biológicas da água.'),
('Naturais','Biológico','1.5.2.3.0', 'Infestações/Pragas', 'Outras infestações', NULL, 'Infestações que alterem o equilíbrio ecológico de uma região, bacia hidrográfica ou bioma afetado por suas ações predatórias.'),

-- DESASTRES TECNOLÓGICOS
-- 1. RADIOLÓGICO
('Tecnológicos','Substâncias radioativas','2.1.1.1.0', 'Desastres siderais com riscos radioativos', 'Queda de satélite (radionuclideos)', NULL, 'Queda de satélites que possuem, na sua composição, motores ou corpos radioativos, podendo ocasionar a liberação deste material.'),
('Tecnológicos','Substâncias radioativas','2.1.2.1.0', 'Desastres com substâncias e equipamentos radioativos de uso em pesquisas, indústrias e usinas nucleares', 'Fontes radioativas em processos de produção', NULL, 'Escapamento acidental de radiação que excede os níveis de segurança estabelecidos na norma NN 3.01/006:2011 da CNEN.'),
('Tecnológicos','Substâncias radioativas','2.1.3.1.0', 'Desastres relacionados com riscos de intensa poluição ambiental provocada por residuos radioativos', 'Outras fontes de liberação de radionuclideos para o meio ambiente', NULL, 'Escapamento acidental ou não acidental de radiação originária de fontes radioativas diversas e que excede os níveis de segurança estabelecidos na norma NN 3.01/006:2011 e NN 3.01/011:2011 da CNEN.'),
-- 2. DESASTRES RELACIONADOS A PRODUTOS PERIGOSOS
('Tecnológicos','Produtos perigosos','2.2.1.1.0', 'Desastres em plantas e distritos industriais, parques e armazenamentos', 'Liberação de produtos químicos para a atmosfera causada por explosão ou incêndio', NULL, 'Liberação de produtos químicos diversos para o ambiente, provocada por explosão/incêndio em plantas industriais ou outros sítios.'),
('Tecnológicos','Produtos perigosos','2.2.2.1.0', 'Desastres relacionados à contaminação da água', 'Liberação de produtos químicos nos sistemas de água potável', NULL, 'Derramamento de produtos químicos diversos em um sistema de abastecimento de água potável, que pode causar alterações nas qualidades físicas, químicas e biológicas.'),
('Tecnológicos','Produtos perigosos','2.2.2.2.0', 'Desastres relacionados à contaminação da água', 'Derramamento de produtos químicos em ambiente lacustre, fluvial, marinho e aquifero', NULL, 'Derramamento de produtos químicos diversos em lagos, rios, mar e reservatórios subterrâneos de água, que pode causar alterações nas qualidades físicas, químicas e biológicas.'),
('Tecnológicos','Produtos perigosos','2.2.3.1.0', 'Desastres relacionados a conflitos bélicos', 'Liberação de produtos químicos e contaminação COMO consequência de ações militares', NULL, 'Agente de natureza nuclear ou radiológica, química ou biológica, considerado como perigoso, e que pode ser utilizado intencionalmente por terroristas ou grupamentos militares em atentados ou em caso de guerra.'),
('Tecnológicos','Produtos perigosos','2.2.4.1.0', 'Desastres relacionados a transporte de produtos perigosos', 'Transporte rodoviário', NULL, 'Extravasamento de produtos perigosos transportados no modal rodoviário.'),
('Tecnológicos','Produtos perigosos','2.2.4.2.0', 'Desastres relacionados a transporte de produtos perigosos', 'Transporte ferroviário', NULL, 'Extravasamento de produtos perigosos transportados no modal ferroviário.'),
('Tecnológicos','Produtos perigosos','2.2.4.3.0', 'Desastres relacionados a transporte de produtos perigosos', 'Transporte aéreo', NULL, 'Extravasamento de produtos perigosos transportados no modal aéreo.'),
('Tecnológicos','Produtos perigosos','2.2.4.4.0', 'Desastres relacionados a transporte de produtos perigosos', 'Transporte dutoviário', NULL, 'Extravasamento de produtos perigosos transportados no modal dutoviário.'),
('Tecnológicos','Produtos perigosos','2.2.4.5.0', 'Desastres relacionados a transporte de produtos perigosos', 'Transporte marítimo', NULL, 'Extravasamento de produtos perigosos transportados no modal marítimo.'),
('Tecnológicos','Produtos perigosos','2.2.4.6.0', 'Desastres relacionados a transporte de produtos perigosos', 'Transporte aquaviário', NULL, 'Extravasamento de produtos perigosos transportados no modal aquaviário.'),
-- 3. INCÊNDIOS URBANOS
('Tecnológicos','Incêndios urbanos','2.3.1.1.0', 'Incêndios urbanos', 'Incêndios em plantas e distritos industriais, parques e depósitos', NULL, 'Propagação descontrolada do fogo em plantas e distritos industriais, parques e depósitos.'),
('Tecnológicos','Incêndios urbanos','2.3.1.2.0', 'Incêndios urbanos', 'Incêndios em aglomerados residenciais', NULL, 'Propagação descontrolada do fogo em conjuntos habitacionais de grande densidade.'),
-- 4. OBRAS CIVIS
('Tecnológicos','Obras civis','2.4.1.0.0', 'Colapso de edificações', NULL, NULL, 'Queda de estrutura civil.'),
('Tecnológicos','Obras civis','2.4.2.0.0', 'Rompimento / colapso de barragens', NULL, NULL, 'Rompimento ou colapso de barragens.'),
-- 5. TRANSPORTE DE PASSAGEIROS E CARGAS NÃO PERIGOSAS
('Tecnológicos','transporte de passageiros e cargas não perigosas','2.5.1.0.0', 'Transporte rodoviário', NULL, NULL, 'Acidente no modal rodoviário envolvendo o transporte de passageiros ou cargas não perigosas.'),
('Tecnológicos','transporte de passageiros e cargas não perigosas','2.5.2.0.0', 'Transporte ferroviário', NULL, NULL, 'Acidente com a participação direta de veículo ferroviário de transporte de passageiros ou cargas não perigosas.'),
('Tecnológicos','transporte de passageiros e cargas não perigosas','2.5.3.0.0', 'Transporte aéreo', NULL, NULL, 'Acidente no modal aéreo envolvendo o transporte de passageiros ou cargas não perigosas.'),
('Tecnológicos','transporte de passageiros e cargas não perigosas','2.5.4.0.0', 'Transporte marítimo', NULL, NULL, 'Acidente com embarcações marítimas destinadas ao transporte de passageiros e cargas não perigosas.'),
('Tecnológicos','transporte de passageiros e cargas não perigosas','2.5.5.0.0', 'Transporte aquaviário', NULL, NULL, 'Acidente com embarcações destinadas ao transporte de passageiros e cargas não perigosas.');
