name: CI - Backend Build & Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  ci-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: backend_test
        ports:
          - 5432:5432
        # garante que o banco está pronto antes de iniciar
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23
          cache: maven

      - name: Build and Test
        shell: bash
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/backend_test
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
        run: |
          if [ -f "backend/pom.xml" ]; then
            cd backend
          fi

          if [ -f "./mvnw" ]; then
            chmod +x ./mvnw
            ./mvnw -B clean verify
          else
            mvn -B clean verify
          fi
